[package]
name = "rocker"
version = "0.1.0"
edition = "2021"
description = "Rocker is a dead-simple tool for generating Rust Dockerfiles"
license = "MIT"

[dependencies]
log = "0.4.0"
env_logger = "0.9.0"
